# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DjangoCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDGRID_SANDBOX_MODE_IN_DEBUG: ${{ secrets.SENDGRID_SANDBOX_MODE_IN_DEBUG }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL}}
      CLOUDINARY_NAME: ${{secrets.CLOUDINARY_NAME}}
      CLOUDINARY_KEY: ${{secrets.CLOUDINARY_KEY}}
      CLOUDINARY_SECRET: ${{secrets.CLOUDINARY_SECRET}}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: system checks
      run: python manage.py check
#     - name: Run tests
#       run: python manage.py test
    - name: Generate Report
      run: |
        pip install coverage
        coverage run manage.py test && coverage report --fail-under=75 && coverage xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
        directory: ./coverage/reports/
        fail_ci_if_error: true
